// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {app} from '../models';

export function ApplyMode(arg1:config.Mode):Promise<app.ActionResult>;

export function BrowseExecutable():Promise<string>;

export function CheckForUpdates():Promise<app.UpdateInfo>;

export function CreateTwitchReward(arg1:string,arg2:number,arg3:string):Promise<app.ActionResult>;

export function GetOBSInventory(arg1:string):Promise<app.OBSInventory>;

export function GetStatus():Promise<app.Status>;

export function GetTwitchRewards():Promise<Array<app.TwitchReward>>;

export function ListRunningProcesses(arg1:app.ProcessListOptions):Promise<Array<app.ProcessSummary>>;

export function RefreshTwitchRewards():Promise<app.ActionResult>;

export function SaveConfig(arg1:app.SettingsInput):Promise<app.ActionResult>;

export function SetReward3DOnly(arg1:string,arg2:boolean):Promise<app.ActionResult>;

export function StartTwitchLogin():Promise<app.ActionResult>;

export function SyncOBS():Promise<app.ActionResult>;

export function Test3DMode():Promise<app.ActionResult>;

export function TestOBSConnection():Promise<app.ActionResult>;

export function TestPNGMode():Promise<app.ActionResult>;
