// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyMode(arg1) {
  return window['go']['main']['App']['ApplyMode'](arg1);
}

export function BrowseExecutable() {
  return window['go']['main']['App']['BrowseExecutable']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CreateTwitchReward(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTwitchReward'](arg1, arg2, arg3);
}

export function GetOBSInventory(arg1) {
  return window['go']['main']['App']['GetOBSInventory'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTwitchRewards() {
  return window['go']['main']['App']['GetTwitchRewards']();
}

export function ListRunningProcesses(arg1) {
  return window['go']['main']['App']['ListRunningProcesses'](arg1);
}

export function RefreshTwitchRewards() {
  return window['go']['main']['App']['RefreshTwitchRewards']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetReward3DOnly(arg1, arg2) {
  return window['go']['main']['App']['SetReward3DOnly'](arg1, arg2);
}

export function StartTwitchLogin() {
  return window['go']['main']['App']['StartTwitchLogin']();
}

export function SyncOBS() {
  return window['go']['main']['App']['SyncOBS']();
}

export function Test3DMode() {
  return window['go']['main']['App']['Test3DMode']();
}

export function TestOBSConnection() {
  return window['go']['main']['App']['TestOBSConnection']();
}

export function TestPNGMode() {
  return window['go']['main']['App']['TestPNGMode']();
}
